from prometheus_client import Counter, Histogram

DOCUMENTS_UPLOADED_TOTAL = Counter(
    "documents_uploaded_total",
    "Total number of documents successfully uploaded to storage.",
)

DOCUMENT_CHUNK_FETCH_DURATION = Histogram(
    "document_chunk_fetch_duration_seconds",
    "Time spent fetching document chunks from the database.",
    labelnames=("operation",),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30),
)

EMBEDDING_GENERATION_DURATION = Histogram(
    "embedding_generation_duration_seconds",
    "Time spent generating vector embeddings for content.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30),
)

CHAT_MESSAGES_FETCH_DURATION = Histogram(
    "chat_messages_fetch_duration_seconds",
    "Time spent fetching chat messages from the database.",
    labelnames=("operation",),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30),
)

LLM_TIME_TO_FIRST_TOKEN = Histogram(
    "llm_time_to_first_token_seconds",
    "Time from starting a chat completion to receiving its first content token.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 30),
)

LLM_STREAM_DURATION = Histogram(
    "llm_stream_duration_seconds",
    "Time from starting a chat completion until its response stream ends.",
    buckets=(0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 30, 60),
)

LLM_INPUT_TOKENS = Counter(
    "llm_input_tokens_total",
    "Total number of input tokens used by chat completions.",
    labelnames=("model",),
)

LLM_OUTPUT_TOKENS = Counter(
    "llm_output_tokens_total",
    "Total number of output tokens generated by chat completions.",
    labelnames=("model",),
)
